# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.21

#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
    base_url: https://hass.madplanet.net:8443

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
      
#Influxdb config
influxdb:
  host: 192.168.0.159
  port: 8086
  ssl: true
  verify_ssl: false
  database: homeassistant
  username: homeassistant
  password: CctW@zVagvtJ5oCK&Tpo
  max_retries: 3
  default_measurement: state

#proxmoxve:
#  - host: 192.168.0.218
#    username: root
#    password: 6euHyQP2L%ZMjqDt
#    nodes:
#      - node: NODE_NAME
#        vms:
#          - VM_ID
#        containers:
#          - CONTAINER_ID

zone:
  - name: Home
    latitude: 51.441581
    longitude: -2.605544
    radius: 80
    icon: mdi:account-multiple

hacs:
    token: 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

circadian_lighting:

# Example configuration.yaml entry

sabnzbd:
  api_key: 85ebc0f2f5b2430b8ea77e9708c53253
  host: sabnzbd.home
  name: sab
  port: 8080
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

ring:
  username: !secret ring_user
  password: !secret ring_pass

downloader:
  download_dir: downloads

switch:
  - platform: flux
    lights:
      - light.hallway_light
      - light.landing_light
    name: Flux
    start_time: '7:00'
    stop_time: '23:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    brightness: 200
    disable_brightness_adjust: true
    mode: mired
    transition: 30
    interval: 60
  - platform: circadian_lighting
    lights_ct:
      - light.hallway_light
      - light.landing_light
    min_brightness: 20

# Synology router
#device_tracker:
#  - platform: synology_srm
#    host: 192.168.0.1
#    username: jhpadmin
#    password: !secret srm_password
#    interval_seconds: 10
#    consider_home: 180
#    new_device_defaults:
#      track_new_devices: true

#device_tracker:
#  - platform: snmp
#    host: 192.168.0.1
#    community: jhpsnmp
#    baseoid: 1.3.6.1.2.1.31.1.1.1
    
# Enable presence based lighting
#device_sun_light_trigger:
#  light_group: group.welcome_lights
#  device_group: group.all_people

sensor:
  # setup system monitoring
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

binary_sensor:
  - platform: ping
    host: 192.168.0.41
    name: front_room_tv
    scan_interval: 30
  - platform: ping
    host: 192.168.0.134
    name: tv_wifi
    scan_interval: 30
  - platform: ping
    host: 192.168.100.1
    name: Virgin_Media_Hub
    scan_interval: 30
  - platform: ping
    host: 151.101.192.81
    name: is_bbc_up
    scan_interval: 30
  - platform: ping
    host: 192.168.0.146
    name: cupboard_ap
    scan_interval: 30
  - platform: ping
    host: 192.168.0.44
    name: kitchen_ap
    scan_interval: 30
  - platform: ping
    host: 192.168.0.145
    name: bedroom2_ap
    scan_interval: 30
  - platform: ping
    host: 192.168.0.199
    name: pi1
    scan_interval: 30
  - platform: template
    sensors:
      office_occupied:
        friendly_name: "Office Occupied"
        value_template: >-
          {{ is_state("sensor.nic_watch_room_presence", "office")
              or is_state("sensor.nic_s_iphone_room_presence", "office")
              or is_state("sensor.jo_s_iphone_room_presence", "office")
          }}
      bedroom1_occupied:
        friendly_name: "Bedroom Occupied"
        value_template: >-
          {{ is_state("sensor.nic_watch_room_presence", "bedroom1")
              or is_state("sensor.nic_s_iphone_room_presence", "bedroom1")
              or is_state("sensor.jo_s_iphone_room_presence", "bedroom1")
          }}
      kitchen_occupied:
        friendly_name: "Kitchen Occupied"
        value_template: >-
          {{ is_state("sensor.nic_watch_room_presence", "kitchen")
              or is_state("sensor.nic_s_iphone_room_presence", "kitchen")
              or is_state("sensor.jo_s_iphone_room_presence", "kitchen")
          }}
      bedroom2_occupied:
        friendly_name: "Bedroom 2 Occupied"
        value_template: >-
          {{ is_state("sensor.nic_watch_room_presence", "bedroom2")
              or is_state("sensor.nic_s_iphone_room_presence", "bedroom2")
              or is_state("sensor.jo_s_iphone_room_presence", "bedroom2")
          }}
      livingroom_occupied:
        friendly_name: "Living Room Occupied"
        value_template: >-
          {{ is_state("sensor.nic_watch_room_presence", "livingroom")
              or is_state("sensor.nic_s_iphone_room_presence", "livingroom")
              or is_state("sensor.jo_s_iphone_room_presence", "livingroom")
          }}

input_number:
  heating_temperature:
    name: Temperature
    initial: 21
    min: 15
    max: 27
    step: 0.5
    icon: mdi:thermometer

input_boolean:
  heating_state:
    name: Heating_switch
    initial: off
    icon: mdi:toggle-switch
  heating_program:
    name: Heating_program_mode
    initial: off
    icon: mdi:toggle-switch
  occupancy:
    name: Occupancy
    icon: mdi:beach

shell_command:
  mount_media: mount -v -t nfs4 192.168.0.21:/volume1/mediastore/media/music /media